#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""armchair-debater - a voice bot that debates theories of consciousness

A cascade pipeline (Speech-to-Text → LLM → Text-to-Speech) driven by the Pipecat
Flows config in flow.yaml. A judge scores each turn in the background and the
debate state is pushed to the client as RTVI server messages.

Generated by Pipecat CLI

Required AI services:
- Gradium (Speech-to-Text)
- General Compute (LLM, via OpenAI-compatible API)
- Gradium (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

from pathlib import Path

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.evals.transport import EvalTransportParams
from pipecat.flows import Flow, FlowConfig, FlowManager
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.workers.runner import WorkerRunner

import handlers
import knowledge
import providers
from debate_state import DebateState
from scorer import TurnScorer
from skip_tts_sync import SkipTTSSync
from turns import TurnObserver
from warmup import start_warmup

load_dotenv(override=True)

FLOW_CONFIG_PATH = Path(__file__).with_name("flow.yaml")


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
    """
    logger.info("Starting bot")

    # Speech-to-Text and Text-to-Speech services (SPEECH_PROVIDER: Gradium by default)
    stt = providers.make_stt()
    tts = providers.make_tts()

    # LLM service (LLM_PROVIDER: General Compute by default, via its
    # OpenAI-compatible API, which is why OpenAI itself is a config change)
    llm_config = providers.llm_config()
    logger.info(
        f"LLM: {llm_config.provider} ({llm_config.model}); speech: {providers.speech_provider()}"
    )
    llm = OpenAILLMService(
        api_key=llm_config.require_key(),
        base_url=llm_config.base_url,
        settings=OpenAILLMService.Settings(model=llm_config.model),
    )

    context = LLMContext()
    context_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(vad_analyzer=SileroVADAnalyzer()),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            context_aggregator.user(),
            llm,
            tts,
            transport.output(),
            context_aggregator.assistant(),
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[],
    )

    runner = WorkerRunner(handle_sigint=runner_args.handle_sigint)

    await runner.add_workers(worker)

    # Join the flow graph to its tools. Constructing the Flow checks that every
    # tool and handler flow.yaml names exists, and reports all misses together.
    flow = Flow(FlowConfig.from_file(FLOW_CONFIG_PATH), handlers=handlers)
    flow_manager = FlowManager(
        worker=worker,
        llm=llm,
        context_aggregator=context_aggregator,
        transport=transport,
        global_functions=flow.global_functions,
    )

    # Every change to the debate state goes to the client as a full snapshot.
    debate = DebateState(on_change=worker.rtvi.send_server_message)
    scorer = TurnScorer(
        debate,
        current_stage=lambda: flow_manager.current_node,
        theories=lambda: (
            flow_manager.state["user_theory_name"],
            flow_manager.state["bot_theory_name"],
        ),
    )
    flow_manager.state.update(
        {"debate": debate, "scorer": scorer, "theory_index": knowledge.index()}
    )

    # Both sides' turns are read from frames rather than aggregator events:
    # the user's from the context frame whose last message is theirs, whether
    # spoken or typed; the bot's from the LLM's own output, which is upstream
    # of TTS and the transport and so immune to the aggregator-event race
    # that used to drop bot turns under an interruption.
    worker.add_observer(TurnObserver(llm, scorer.submit))
    # Text-mode evals ask for no speech; see skip_tts_sync.py for why they got it anyway.
    worker.add_observer(SkipTTSSync(worker.rtvi, worker.queue_frame))

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # The select screen needs the cards before the first debate snapshot.
        await rtvi.send_server_message({"type": "theory_cards", "cards": knowledge.client_cards()})
        await flow_manager.initialize(flow.initial_node)

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")
        # Fire-and-forget: warm the LLM endpoint so the greeting's first
        # request isn't the one paying the cold-start latency. This is plain
        # application code outside any Pipecat BaseObject, so asyncio.create_task
        # (inside start_warmup) is correct here, not self.create_task. The task
        # is owned by warmup.py, not by this handler, so it survives a fast
        # disconnect that tears down this session before the warm-up finishes.
        start_warmup()

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        # A turn still with the judge would otherwise be applied, and sent, to
        # a session that no longer exists.
        scorer.abandon()
        await runner.cancel()

    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport_params = {
        "webrtc": lambda: TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        # Behavioral evals: run with `-t eval` to drive this bot via `pipecat eval`.
        "eval": lambda: EvalTransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    }

    transport = await create_transport(runner_args, transport_params)

    await run_bot(transport, runner_args)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
