#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""armchair-debater - a voice bot that debates theories of consciousness

A cascade pipeline (Speech-to-Text → LLM → Text-to-Speech) driven by the Pipecat
Flows config in flow.yaml. A judge scores each turn in the background and the
debate state is pushed to the client as RTVI server messages.

Generated by Pipecat CLI

Required AI services:
- Gradium (Speech-to-Text)
- General Compute (LLM, via OpenAI-compatible API)
- Gradium (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.evals.transport import EvalTransportParams
from pipecat.flows import Flow, FlowConfig, FlowManager
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.services.gradium.stt import GradiumSTTService
from pipecat.services.gradium.tts import GradiumTTSService
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.workers.runner import WorkerRunner

import handlers
import knowledge
from debate_state import DebateState
from scorer import TurnScorer

load_dotenv(override=True)

FLOW_CONFIG_PATH = Path(__file__).with_name("flow.yaml")


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
    """
    logger.info("Starting bot")

    # Speech-to-Text service
    stt = GradiumSTTService(api_key=os.getenv("GRADIUM_API_KEY"))

    # Text-to-Speech service
    tts = GradiumTTSService(
        api_key=os.getenv("GRADIUM_API_KEY"),
        settings=GradiumTTSService.Settings(
            voice=os.getenv("GRADIUM_VOICE_ID", "_6Aslh2DxfmnRLmP"),
        ),
    )

    # LLM service (General Compute, via its OpenAI-compatible API)
    llm = OpenAILLMService(
        api_key=os.getenv("GENERAL_COMPUTE_API_KEY"),
        base_url="https://api.generalcompute.com/v1",
        settings=OpenAILLMService.Settings(
            model=os.getenv("GENERAL_COMPUTE_MODEL", "deepseek-v3.2"),
        ),
    )

    context = LLMContext()
    context_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(vad_analyzer=SileroVADAnalyzer()),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            context_aggregator.user(),
            llm,
            tts,
            transport.output(),
            context_aggregator.assistant(),
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[],
    )

    runner = WorkerRunner(handle_sigint=runner_args.handle_sigint)

    await runner.add_workers(worker)

    # Join the flow graph to its tools. Constructing the Flow checks that every
    # tool and handler flow.yaml names exists, and reports all misses together.
    flow = Flow(FlowConfig.from_file(FLOW_CONFIG_PATH), handlers=handlers)
    flow_manager = FlowManager(
        worker=worker,
        llm=llm,
        context_aggregator=context_aggregator,
        transport=transport,
        global_functions=flow.global_functions,
    )

    # Every change to the debate state goes to the client as a full snapshot.
    debate = DebateState(on_change=worker.rtvi.send_server_message)
    scorer = TurnScorer(
        debate,
        current_stage=lambda: flow_manager.current_node,
        theories=lambda: (
            flow_manager.state["user_theory_name"],
            flow_manager.state["bot_theory_name"],
        ),
    )
    flow_manager.state.update(
        {"debate": debate, "scorer": scorer, "theory_index": knowledge.index()}
    )

    # Finished turns are scored in the background; submit() never blocks.
    @context_aggregator.user().event_handler("on_user_turn_message_added")
    async def on_user_turn_message_added(aggregator, message):
        scorer.submit("user", message.content or "")

    @context_aggregator.assistant().event_handler("on_assistant_turn_stopped")
    async def on_assistant_turn_stopped(aggregator, message):
        scorer.submit("bot", message.content or "")

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        await flow_manager.initialize(flow.initial_node)

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await runner.cancel()

    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport_params = {
        "webrtc": lambda: TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        # Behavioral evals: run with `-t eval` to drive this bot via `pipecat eval`.
        "eval": lambda: EvalTransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    }

    transport = await create_transport(runner_args, transport_params)

    await run_bot(transport, runner_args)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
